In [2]:
import numpy as np

# Part 1: Creating ndarrays

1. Convert the below given list of strings to an int32 NumPy array

In [14]:
slist = ['2.5', '1.25', '0.024','2.999','1024.5']
l=['1','2','3']

In [21]:
# Write your code here
#type(slist)
a = np.array(slist)
print(a)
b = a.astype(np.float)
print(b)
c= b.astype(np.int32)
print(c)

['2.5' '1.25' '0.024' '2.999' '1024.5']
[2.5000e+00 1.2500e+00 2.4000e-02 2.9990e+00 1.0245e+03]
[   2    1    0    2 1024]


In [19]:
a = np.array(l)
b = a.astype(np.int32)
print(b)

[1 2 3]


2. Create an empty 5x5 NumPy matrix

In [23]:
# Write your code here
e= np.empty((5,5))

# Part 2: Operations between Arrays and Scalars

3. Create a 1x7 Numpy array whose elements consist of a geometric progression with a = 1 & r = 3, terms are arranged indexwise, for ex

In [9]:
sample_output = [1,3,9,27,81]

In [26]:
# Write your code here
np.geomspace(1, 81, num=5, dtype=int)

array([ 1,  3,  9, 27, 81])

4. Transform each of the element of the below matrix according to the below equation

    if x is an elements in input matrix, output matrix should have 
$1/(x^2 + 1)$ in its place



In [27]:
mat = [[1,2,3],[4,5,6]]

In [28]:
# Write your code here
def func(x):
    return 1/(1+(x*x))
m=np.array(mat)
func(m)

array([[0.5       , 0.2       , 0.1       ],
       [0.05882353, 0.03846154, 0.02702703]])

# Part 3: Basic Indexing and Slicing

5. Make a 5x5 NumPy array of all zeros and use indexing and broadcasting to modify it such that all the elements not on the border are 1, for example

In [29]:
output_sample = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,1,1,0],[0,1,1,1,0],[0,0,0,0,0]])
output_sample

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [31]:
#write your code here
x = np.zeros((5,5),dtype=int)
x[1:-1,1:-1] = 1
print(x)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


6. Given the 3x3x3, 3-dimensional NumPy array

In [33]:
arr = np.arange(27).reshape((3,3,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

i. Slice this matrix to contain only second and third rows, first and second columns of the given matrix.

In [ ]:
sample_output = np.array([[[3,4],[6,7]],[[12,13],[15,16]],[[21,22],[24,25]]])
sample_output

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

In [36]:
#write your code here
ans=arr[0:3,1:3,0:2]
ans

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

ii. Output a two dimensional matrix as shown below

In [ ]:
arr = np.arange(27).reshape((3,3,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
sample_output = np.array([[0,3,6],[9,12,15],[18,21,14]])
sample_output

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 14]])

In [71]:
temp=arr[0,0:3,0:1]
#print(temp)
#print(np.transpose(t))
final=np.empty((3,3),dtype=int)
final[0] = np.transpose(temp)
temp=arr[1,0:3,0:1]
final[1] = np.transpose(temp)
temp=arr[2,0:3,0:1]
final[2] = np.transpose(temp)
final

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [55]:
#write your code here
ans=arr[0:1,0:3,0:1]
final=np.empty((3,3),dtype=int)
final[0]=np.transpose(ans[0])
ans=arr[1:2,0:3,0:1]
final[1]=np.transpose(ans[0])
ans=arr[2:3,0:3,0:1]
final[2]=np.transpose(ans[0])
final

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

# Part 4: Boolean Indexing

7. Given the following array, modify it such that even values stay the same and output contains 0s instead of odd values

In [72]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
sample_output = np.array([[0,0,2],[0,4,0],[6,0,8]])
sample_output

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

In [ ]:
# Write your code here
a=arr
a[a%2==1] = 0  
a

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

# Part 5: Fancy Indexing

8. For the given matrix, use fancy indexing to output a 2d matrix consisting all the even elements of the given matrix

In [83]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
sample_output = np.array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])
sample_output

In [87]:
final = np.empty((8,2),dtype=int)
final[0:8,0]=arr[0:8,0]
final[0:8,1]=arr[0:8,2]
final

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

# Part 6: Expressing Conditional Logic as Array Operations



Given two following matrices, use conditional logic to replace all the odd elements of matrix A with even elements of matrix B

In [90]:
A = np.arange(9).reshape((3,3))
B = np.arange(1,10).reshape((3,3))
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
sample_output = np.array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])
sample_output

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

In [ ]:
A=np.where((A %2 ==1) & (B %2 ==0), B,A )
A

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

# Part 7: Linear Algebra

Given the following system of equations, solve for x and y using either `numpy.linalg.solve(m1,m2)` or using `inv` and `dot`

2x + 5y = 20

3x + 6y = 12

In [ ]:
#write your code here
a=np.array([[2,5],[3,6]])
b=np.array([20,12])
np.linalg.solve(a,b)

array([-20.,  12.])